module.exports = {
  future: {
    purgeLayersByDefault: true,
    applyComplexClasses: true,
  },
  purge: {
    content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      './components/**/*.{js,ts,jsx,tsx}',
    ],
    options: {
      safelist: {
        standard: ['outline-none'],
      },
    },
  },
  variants: {
    fill: ['hover', 'focus'],
  },
  variants: {
    extend: {
      display: ['group-hover'],
    },
  },
  theme: {
    extend: {
      listStyleType: {
        arrow: '→',
      },
      animation: {
        ping: "ping 3s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
      zIndex: {
        overlay: '9999',
      },
      spacing: {
        opt1right: '174px',
        opt1top: '65px',
        smopt1right: '45px',
        smopt1top: '29px',
        opt2right: '174px',
        opt2top: '289px',
        smopt2right: '45px',
        smopt2top: '133px',
        opt3right: '818px',
        opt3top: '75px',
        smopt3right: '343px',
        smopt3top: '35px',
        opt4right: '821px',
        opt4top: '193px',
        smopt4right: '343px',
        smopt4top: '89px',
        opt5right: '821px',
        opt5top: '536px',
        smopt5right: '343px',
        smopt5top: '247px',
        opt6right: '818px',
        opt6top: '421px',
        smopt6right: '342px',
        smopt6top: '194px',
        opt7right: '174px',
        opt7top: '175px',
        smopt7right: '44px',
        smopt7top: '81px',
        opt8right: '551px',
        opt8top: '649px',
        smopt8right: '219px',
        smopt8top: '300px',
        opt9right: '433px',
        opt9top: '650px',
        smopt9right: '164px',
        smopt9top: '300px',
        opt10right: '174px',
        opt10top: '396px',
        smopt10right: '44px',
        smopt10top: '182px',
        opt11right: '165px',
        opt11top: '540px',
        smopt11right: '40px',
        smopt11top: '249px',
        opt12right: '164px',
        opt12top: '653px',
        smopt12right: '40px',
        smopt12top: '302px',
        opt13right: '821px',
        opt13top: '660px',
        smopt13right: '343px',
        smopt13top: '305px',
        opt14right: '84px',
        opt14top: '469px',
        smopt14right: '2px',
        smopt14top: '216px',
        opt15right: '817px',
        opt15top: '311px',
        smopt15right: '342px',
        smopt15top: '144px',
        dspace: '31rem',
        imagepopupheight: '560px',
        imagepopupwidth: '800px',
        maslowimage: '720px',
        banTop: '771px',
        mobileBanTop: '771px',
        banLeft: '18%',
        sliderImage:'600px'
      },
      height: {
        CatBanner: '47rem',
        StaticBanner: '32rem',
        mx1162h: '1000px',
        cartside: '28rem',
        cartsidesm: '27rem',
        newbanner: '950px',
        cartVH:'60vh',
        imageComparisionHeight: '700px',
        mobileImageComparisionHeight: '465px'
      },
      width: {
        mx1162w: '1000px',
        61: '75%',
        41: '25%',
        menuWidth: '450px'
      },
      maxWidth: {
        '9xl': '1920px',
        '8xl': '1540px',
      },
      colors: {
        truemed:"#183b43",
        truemedHover:"#206879",
        primary: 'var(--primary)',
        'primary-2': 'var(--primary-2)',
        secondary: 'var(--secondary)',
        'secondary-2': 'var(--secondary-2)',
        hover: 'var(--hover)',
        'hover-1': 'var(--hover-1)',
        'hover-2': 'var(--hover-2)',
        'accent-0': 'var(--accent-0)',
        'accent-1': 'var(--accent-1)',
        'accent-2': 'var(--accent-2)',
        'accent-3': 'var(--accent-3)',
        'accent-4': 'var(--accent-4)',
        'accent-5': 'var(--accent-5)',
        'accent-6': 'var(--accent-6)',
        'accent-7': 'var(--accent-7)',
        'accent-8': 'var(--accent-8)',
        'accent-9': 'var(--accent-9)',
        violet: 'var(--violet)',
        'violet-light': 'var(--violet-light)',
        'violet-dark': 'var(--violet-dark)',
        pink: 'var(--pink)',
        'pink-light': 'var(--pink-light)',
        cyan: 'var(--cyan)',
        blue: 'var(--blue)',
        green: 'var(--green)',
        red: 'var(--red)',
        'white-f2f9fa': '#F2F9FA',
        'red-bc2026': '#BC2026',
        'red-hover': '#da3c3c',
        'black-373933': '#373933',
        'black-1c2023': '#1C2023',
        'gray-char': '#CECECE',
        'grey-848484': '#848484',
        'grey-8C8C8C': '#8C8C8C',
        'bread-59bec9': '#59bec9',
        affirm: '#4A4AF4',
        paytomorrow: '#18A0FB',
        mysynchrony: '#fbc600',
        mysynchronySec: '#34657f',
        timepayment: '#2D8000',
        wegetfinancing: '#3973b9',
        darkgunmetal: '#1B252F',
        archbanner: '#F2CC32',
        customgray:'#242424',
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
      },
      boxShadow: {
        'outline-normal': '0 0 0 2px var(--accent-2)',
        magical:
          'rgba(0, 0, 0, 0.02) 0px 30px 30px, rgba(0, 0, 0, 0.03) 0px 0px 8px, rgba(0, 0, 0, 0.05) 0px 1px 0px',
      },
      lineHeight: {
        'extra-loose': '2.2',
      },
      scale: {
        120: '1.2',
      },
      fontSize: {
        categoryHead: '90px',
        bannerTitle: '7.6rem',
        headerText: '70px',
        threedtext: '10rem',
      },
      backgroundImage: {
        'loyalty-image': "url('/LoyaltyProgram/coverImageLoy.jpg')",
        'referFriend-image': "url('/LoyaltyProgram/referFriend.jpg')",
        'portfolio-image': "url('/Portfolio/coverImage.jpg')",
        'portfolio-project-image': "url('/PortfolioProject/coverImage.jpg')",
        'manuals-image': "url('/Manuals/coverImage.jpg')",
        'abductor-manuals-image': "url('/Manuals/abductor.jpg')",
        'latPulldown-manuals-image': "url('/Manuals/latPulldown.jpg')",
        'legPress-manuals-image': "url('/Manuals/legPress.jpg')",
        'blog-image': "url('/Blog/coverImage.jpg')",
        'blog-article1-image': "url('/Blog/1.jpg')",
        'blog-article2-image': "url('/Blog/2.jpg')",
        'blog-article3-image': "url('/Blog/3.jpg')",
        'blogArticle-image': "url('/BlogArticle/banner.jpg')",
        'blogArticle-art1-image': "url('/BlogArticle/article1.jpg')",
        'blogArticle-art2-image': "url('/BlogArticle/article2.jpg')",
        'blogArticle-art3-image': "url('/BlogArticle/article3.jpg')",
        'cat-packages-image': "url('/CatPackages/coverImage.jpg')",
        'catPack-videoSec-image': "url('/CatPackages/videoSection.jpg')",
        'allProducts-image': "url('/AllProducts/bannerImg.jpg')",
        'allPackages-universal': "url('/AllPackages/universal.png')",
        'allPackages-freeWeight': "url('/AllPackages/freeWeight.png')",
        'allPackages-weightRoom': "url('/AllPackages/weightRoom.png')",
        'allPackages-garage': "url('/AllPackages/garage.png')",
        'allPackages-home': "url('/AllPackages/home.png')",
        'allPackages-dynamic': "url('/AllPackages/dynamic.png')",
        'benches-image': "url('/Category/cover-image-benches.png')",
        'mid-banner': "url('/Category/midBanner-img.png')",
        'contact-image': "url('/Contact/main-banner.png')",
        'sled-mainbanner': "url('/sledproduct/herophoto.webp')",
        'sledpro-mainbanner': "url('/SledPro/banner.jpg')",
        'sledpro-tesla': "url('https://cms.bodykore.com/uploads/Sled_Pro3_26151498c6.webp')",
        'sledpro-bottomimage': "url('https://cms.bodykore.com/uploads/sledbanner_0dfe364c50.webp')",
        '3Dsledpro': "url('https://cms.bodykore.com/uploads/3_D_Sled_scaled_70854a769f.jpg')",
        'sledzoom': "url('https://cms.bodykore.com/uploads/sledzoom_d821a2a803.jpg')",
        'maslow-banner': "url('https://cms.bodykore.com/uploads/Maslow_Hero_Banner_desktop_bfce3a723d.webp')",
        'maslow-banner-mobile': "url('https://cms.bodykore.com/uploads/Maslow_Hero_Banner_mobile_02bc20b690.webp')",
        'maslow-yellow-bar': "url('https://cms.bodykore.com/uploads/yellowbanner_d693839810.png')",
        'partner': "url('https://cdn.shopify.com/s/files/1/0609/8898/1468/files/whatWeDo.avif')",
        
        
        'sled-poweredby': "url('/sledproduct/poweredby.jpg')",
        'universaltrainer-mainbanner':
          "url('https://cms.bodykore.com/uploads/mx1162_gallery_15_5c60ff80e6.jpeg')",
        'universaltrainer-mainbannerr':
          "url('/functionaltraining/banner11.jpg')",
        breadpay: "url('/bread/breadbanner.svg')",
        bgImage: "url('/finance/coverImageFin.jpg')",
        bgImage_mx1162: "url('/mx1162.jpg')",
        popupbg: "url('/banner/popupbg.jpeg')",
        squatbox: "url('/squatbox/02.jpg')",
        left3d:
          "url('https://cms.bodykore.com/uploads/Arcadia01_6f2d23bb64.jpg')",
      },
      fontFamily: {
        bebas: ['Bebas Neue'],
        roboto: ['"Roboto"', 'sans-serif'],
        'acumin-pro': ['"acumin-pro"', 'sans-serif'],
        playfair: ['"Playfair Display"', 'serif'],
        montserrat: ['"Montserrat"', 'sans-serif'],
        Archivo: ['"Archivo"', 'sans-serif'],
      },
      fontWeight: {
        hairline: 100,
        thin: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
      },

      keyframes: {
        zoomBlack: {
          '0%': {
            background: 'rgba(0,0,0,0.5)',
          },
          '100%': {
            background: 'rgba(0,0,0,0)',
          },
        },
      },
    },
    container: {
      center: true,
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
    fontSize: {
      xxs: '.375rem',
      xs: '.75rem',
      sm: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
      '9xl': '7rem',
      '2.25xl': '2.25rem',
      'main-banner-title': '6rem',
    },
  },
};
